# This rule is not used by the project platform-service-openbao itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to openbao.open-control-plane.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: platform-service-openbao
    app.kubernetes.io/managed-by: kustomize
  name: policybinding-viewer-role
rules:
- apiGroups:
  - openbao.open-control-plane.io
  resources:
  - policybindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openbao.open-control-plane.io
  resources:
  - policybindings/status
  verbs:
  - get
