# This rule is not used by the project platform-service-openbao itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete openbao.open-control-plane.io serviceconfigs.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: platform-service-openbao
    app.kubernetes.io/managed-by: kustomize
  name: serviceconfig-editor-role
rules:
- apiGroups:
  - openbao.open-control-plane.io
  resources:
  - serviceconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openbao.open-control-plane.io
  resources:
  - serviceconfigs/status
  verbs:
  - get
