## Append samples of your project ##
resources:
- openbao_v1alpha1_serviceconfig.yaml
- openbao_v1alpha1_openbaoinstance.yaml
- openbao_v1alpha1_projectentity.yaml
- openbao_v1alpha1_controlplanetrust.yaml
- openbao_v1alpha1_controlplaneentity.yaml
- openbao_v1alpha1_policybinding.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
