apiVersion: openbao.open-control-plane.io/v1alpha1
kind: ControlPlaneEntity
metadata:
  labels:
    app.kubernetes.io/name: platform-service-openbao
    app.kubernetes.io/managed-by: kustomize
  name: controlplaneentity-sample
spec:
  # TODO(user): Add fields here
